Fix error when creating environment estimate_filtering_params
This fixes an error which suddenly started appearing, probably due to a change of the packages in one of the channels:
CreateCondaEnvironmentException:                                                                                                                                                                                                                
Could not create conda environment from workflow/rules/../envs/estimate_filtering_params.yaml:                                                                      
Encountered problems while solving:                                                                                                                                                                                                             
  - package scikit-allel-1.3.1-py38hcb8c335_0 is excluded by strict repo priority